### ISSUE TITLE
[Map] GHG installations are no longer showing up on the map

### ISSUE THREAD

**Issue by beets** [datacommonsorg/website#1462] opened 2022-02-25 01:19 UTC
### Describe the bug
Expect to see installations from the link on the map landing page. It's still working in prod, but not on autopush or dev

### To Reproduce
URL:  https://autopush.datacommons.org/tools/map#%26sv%3DAnnual_Emissions_GreenhouseGas_NonBiogenic%26pc%3D0%26denom%3DCount_Person%26pd%3DgeoId%2F48%26ept%3DCounty%26ppt%3DEpaReportingFacility%26mp%3D1

### Screenshots
Prod: 
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/6052978/155635073-5239e6af-4361-4266-8b4c-c8e5b94b05a4.png">

Autopush:
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/6052978/155635100-625f9029-2b4d-4134-8571-ef8b753cd0c1.png">

### Additional info:

There doesn't seem to be API errors, and [the request for EpaReportingFacility](https://autopush.datacommons.org/api/choropleth/map-points?placeDcid=geoId/48&placeType=EpaReportingFacility) is still being made with results returned.

**Comment by beets** [comment] 2022-02-25 01:23
Relatedly, glacier's are also missing (but this is also missing in prod)
https://datacommons.org/tools/map#%26sv%3DDifferenceRelativeToBaseDate2006_Max_Temperature_RCP45%26pc%3D0%26denom%3DCount_Person%26mapsv%3DSurfaceArea%26pd%3Dasia%26ept%3DIPCCPlace_50%26ppt%3DGlacier%26mp%3D1

https://datacommons.org/api/choropleth/map-points?placeDcid=asia&placeType=Glacier  returns {}

**Comment by chejennifer** [comment] 2022-02-25 17:37
> ### Describe the bug
> Expect to see installations from the link on the map landing page. It's still working in prod, but not on autopush or dev
> 
> ### To Reproduce
> URL: https://autopush.datacommons.org/tools/map#%26sv%3DAnnual_Emissions_GreenhouseGas_NonBiogenic%26pc%3D0%26denom%3DCount_Person%26pd%3DgeoId%2F48%26ept%3DCounty%26ppt%3DEpaReportingFacility%26mp%3D1
> 
> ### Screenshots
> Prod: <img alt="image" width="1366" src="https://user-images.githubusercontent.com/6052978/155635073-5239e6af-4361-4266-8b4c-c8e5b94b05a4.png">
> 
> Autopush: <img alt="image" width="1366" src="https://user-images.githubusercontent.com/6052978/155635100-625f9029-2b4d-4134-8571-ef8b753cd0c1.png">
> 
> ### Additional info:
> There doesn't seem to be API errors, and [the request for EpaReportingFacility](https://autopush.datacommons.org/api/choropleth/map-points?placeDcid=geoId/48&placeType=EpaReportingFacility) is still being made with results returned.

I think this actually is an API error. The API for getting the data values for the installations is returning empty for both dev and autopush, but has values for prod. This is true for both the flask endpoints and the Mixer endpoints.

The flask endpoint: https://autopush.datacommons.org/api/stats/within-place?parent_place=geoId/48&child_type=EpaReportingFacility&stat_vars=Annual_Emissions_GreenhouseGas_NonBiogenic

The Mixer endpoint: https://autopush.api.datacommons.org/stat/set/within-place?parentPlace=geoId%2F48&childType=EpaReportingFacility&statVars=Annual_Emissions_GreenhouseGas_NonBiogenic

**Comment by beets** [comment] 2022-02-25 18:17
Ah, yes - we have not pushed out Glaciers, which is why that is missing from prod.

I'll move this issue over to the mixer repo

**Comment by beets** [comment] 2022-02-25 18:47
argh i can't transfer this issue to mixer.

so it seems it's not aggregating up to state / country, and this is happening on autopush too.

**Both work**
[dev - zip level](https://dev.api.datacommons.org/stat/set/within-place?parentPlace=zip/73114&childType=EpaReportingFacility&statVars=Annual_Emissions_GreenhouseGas_NonBiogenic)
[autopush - zip level](https://autopush.api.datacommons.org/stat/set/within-place?parentPlace=zip/73114&childType=EpaReportingFacility&statVars=Annual_Emissions_GreenhouseGas_NonBiogenic)

[dev - county level](https://dev.api.datacommons.org/stat/set/within-place?parentPlace=geoId/40109&childType=EpaReportingFacility&statVars=Annual_Emissions_GreenhouseGas_NonBiogenic)
[autopush - county level](https://autopush.api.datacommons.org/stat/set/within-place?parentPlace=geoId/40109&childType=EpaReportingFacility&statVars=Annual_Emissions_GreenhouseGas_NonBiogenic)

**Both doesn't work**
[dev - state level](https://dev.api.datacommons.org/stat/set/within-place?parentPlace=geoId/40&childType=EpaReportingFacility&statVars=Annual_Emissions_GreenhouseGas_NonBiogenic)
[autopush - state level](https://dev.api.datacommons.org/stat/set/within-place?parentPlace=geoId/40&childType=EpaReportingFacility&statVars=Annual_Emissions_GreenhouseGas_NonBiogenic)
Note: this works in prod / staging

**Comment by chejennifer** [comment] 2022-02-25 18:58
> Relatedly, glacier's are also missing (but this is missing in prod, working in dev) https://datacommons.org/tools/map#%26sv%3DDifferenceRelativeToBaseDate2006_Max_Temperature_RCP45%26pc%3D0%26denom%3DCount_Person%26mapsv%3DSurfaceArea%26pd%3Dasia%26ept%3DIPCCPlace_50%26ppt%3DGlacier%26mp%3D1
> 
> https://datacommons.org/api/choropleth/map-points?placeDcid=asia&placeType=Glacier returns {}
> 
> That map doesn't load on autopush because this is returning 500: https://autopush.datacommons.org/api/stats/set/series/within-place?parent_place=asia&child_type=IPCCPlace_50&stat_vars=Count_Person
> 
> This is pretty strange behavior..

Glaciers are not pushed to prod yet, but there is something strange happening with the API causing the map to not load on autopush due to api/stats/set/series/within-place returning 500.

It looks like the /stat/set/series/within-place endpoint on autopush (both dev and prod are fine though) is complaining about missing places argument although that is not an argument for the endpoint:
[autopush](https://autopush.api.datacommons.org/stat/set/series/within-place?parentPlace=asia&childType=IPCCPlace_50&statVars=Count_Person)
[dev](https://dev.api.datacommons.org/stat/set/series/within-place?parentPlace=asia&childType=IPCCPlace_50&statVars=Count_Person)
[prod](https://api.datacommons.org/stat/set/series/within-place?parentPlace=asia&childType=IPCCPlace_50&statVars=Count_Person)

**Comment by chejennifer** [comment] 2022-02-25 19:08
> Relatedly, glacier's are also missing (but this is missing in prod, working in dev) https://datacommons.org/tools/map#%26sv%3DDifferenceRelativeToBaseDate2006_Max_Temperature_RCP45%26pc%3D0%26denom%3DCount_Person%26mapsv%3DSurfaceArea%26pd%3Dasia%26ept%3DIPCCPlace_50%26ppt%3DGlacier%26mp%3D1
> 
> https://datacommons.org/api/choropleth/map-points?placeDcid=asia&placeType=Glacier returns {}
> 
> That map doesn't load on autopush because this is returning 500: https://autopush.datacommons.org/api/stats/set/series/within-place?parent_place=asia&child_type=IPCCPlace_50&stat_vars=Count_Person
> 
> This is pretty strange behavior..

It looks like the map not being returned on autopush due to api/stats/set/series/within-place might be a data/API problem. It looks like on autopush (dev and prod are fine), api/stats/set/series/within-place is getting an empty list when calling GetChildPlaces for IPCC50 in asia

**Comment by shifucun** [comment] 2022-02-25 19:27
Thanks for the investigation. I sent a fix in https://github.com/datacommonsorg/mixer/pull/754. The issue is due to a partial cleanup of PlacesIn API and a non-merging version is used now.

**Comment by shifucun** [comment] 2022-02-25 20:07
Fixed in autopush now. I will push to dev soon.

**Closed by shifucun** 2022-02-25 20:07 UTC
Labels: bug

**Comment by beets** [comment] 2022-02-25 20:32
thanks for the quick fix!
