### ISSUE TITLE
[BUG] when per capita is selected, sometimes scale has no contrast

### ISSUE THREAD

**Issue by chejennifer** [datacommonsorg/website#1566] opened 2022-04-19 15:25 UTC
eg. http://localhost:8080/tools/map#%26sv%3DCount_Person_Employed%26pc%3D1%26denom%3DCount_Person%26pd%3Dcountry%2FUSA%26ept%3DCounty%26domain%3D8106479329266892%3A4053239664633446%3A0

**Comment by beets** [comment] 2022-04-19 16:30
Marking this as duplicate of #1167 -- we can add these as examples to look out for there.

**Closed by beets** 2022-04-19 16:30 UTC
